#!/bin/bash
HERE="$(dirname "$(readlink -f "${0}")")"
GAME_DIR=aoeu
GAME_EXEC=game.sh
export LD_LIBRARY_PATH=${HERE}/$GAME_DIR/:${HERE}/usr/lib:$LD_LIBRARY_PATH
cd "${HERE}/$GAME_DIR"
"${HERE}/$GAME_DIR/$GAME_EXEC" "$@"
exit $?
